apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-cloudhsm-2223
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: vmc
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  hosts:
  - cloudhsm-2223.tcp.svc
  gateways:
  - mesh
  tcp:
  - match:
    - gateways:
      - mesh
      destinationSubnets:
      - {{ .Values.global.cloudHsm.ip }}/32
      port: 2223
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: {{ .Release.Name }}-vmc-cloudhsm-2223
        port:
          number: 443
  exportTo:
  - "."
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-cloudhsm-2224
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: vmc
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  hosts:
  - cloudhsm-2224.tcp.svc
  gateways:
  - mesh
  tcp:
  - match:
    - gateways:
      - mesh
      destinationSubnets:
      - {{ .Values.global.cloudHsm.ip }}/32
      port: 2224
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: {{ .Release.Name }}-vmc-cloudhsm-2224
        port:
          number: 443
  exportTo:
  - "."
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-cloudhsm-2225
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: vmc
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  hosts:
  - cloudhsm-2225.tcp.svc
  gateways:
  - mesh
  tcp:
  - match:
    - gateways:
      - mesh
      destinationSubnets:
      - {{ .Values.global.cloudHsm.ip }}/32
      port: 2225
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: {{ .Release.Name }}-vmc-cloudhsm-2225
        port:
          number: 443
  exportTo:
  - "."
